# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eric Watkins
title: Web Developer
email: eric.r.watkins@gmail.com
website: www.github.com/ericdub

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Carlos_TheDwarf
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I'm Eric! I've been playing around with Web stuff since 2002, for work and fun. I have quite a bit of expereince with front-end developement but am most comfortable ubnder the hood.

  My primary skills are: <mark>PHP</mark>,<mark>Javascript</mark>,<mark>MySQL</mark>,<mark>Apache</mark>,<mark>Twig</mark>, and <mark>CSS</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Daniel Boone Regional Library
        link: dbrl.org
        # link_text: boringcompany.com
        sub_title: Web Coordinator
        caption: March 2012 - June 2014
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Resposible design and development for the library's digital branch, including the public site, community digital archive,integration of online catalog software, and events calendar. 

      - layout: left
        title: Stephens College 
        link: stephens.edu
        # link_text: boringcompany.com
        sub_title: Webmaster
        caption: September 2006 - February 2012
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Acted as a one man dev shop, handling front-end UX and all backend funcitonality for the college's entire online presence, including donations, admissions, and alumna portal.
    
      - layout: left
        title: University of Missouri - Columbia
        link: missouri.edu
        # link_text: boringcompany.com
        sub_title: Internet Administrator
        caption: October 2002 - September 2006
        quote: >
          
        description: | # this will include new lines to allow paragraphs
             I was a founding member of Mizzou's Web Communications team. Dreamweaver baby! I set up their first offical blog, email newsletter, and analytics.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Missouri - Columbia
        caption: 2010 - 2013
        sub_title: 1996-2000
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I very quickly figured out I had no interest at all in being a journalist, but loved messing about on the Web. I taught myself HTML and well, here I am.

  # #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  #   - title: Experience # Title for the section
  #     layout: list # Type of content section (list/text)
  #     content:
  #       - layout: left
  #         title: Stephens College 
  #         link: stephens.edu
  #         # link_text: boringcompany.com
  #         sub_title: Webmaster
  #         caption: October 2002 - September 2006
            
  #         description: | # this will include new lines to allow paragraphs
  #               I was a founding member of Mizzou's Web Communications team. Dreamweaver baby! I set up their first offical blog, email newsletter, and analytics.



  #     - title: Education # Title for the section
  #       layout: list # Type of content section (list/text)
  #       content:
  #         - layout: left
  #           title: University of Missouri - Columbia
  #           caption: 1996-2000
  #           sub_title: BJ Journalism
          
  #           description: | # this will include new lines to allow paragraphs
  #           I very quickly figured out I had no interest at all in being a journalist, but loved messing about on the Web. I taught myself HTML and well, here I am.

         

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in the Web some of my other interests and hobbies are:
      - Running
      - Gaming
      - Kayaking
      - Hiking
      - Cycling

      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
